import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { Conversation } from '@/types/chat';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function exportConversation(conversation: Conversation, format: 'md' | 'txt') {
  if (typeof window === 'undefined') return;
  
  let content = '';
  
  if (format === 'md') {
    content = `# ${conversation.title}\n\n`;
    content += `*Generated by Aeva v0.1 | Date: ${new Date(conversation.createdTime).toLocaleDateString()}*\n\n---\n\n`;
    
    conversation.messages.forEach((msg) => {
      const roleName = msg.role === 'user' ? 'User' : 'Aeva';
      content += `### ${roleName}\n\n${msg.content}\n\n---\n\n`;
    });
  } else {
    content = `AEVA CHAT EXPORT\n`;
    content += `Title: ${conversation.title}\n`;
    content += `Date: ${new Date(conversation.createdTime).toLocaleString()}\n`;
    content += `==========================================\n\n`;
    
    conversation.messages.forEach((msg) => {
      const roleName = msg.role === 'user' ? 'USER' : 'AEVA';
      content += `[${roleName}] (${new Date(msg.timestamp).toLocaleTimeString()})\n`;
      content += `${msg.content}\n`;
      content += `------------------------------------------\n\n`;
    });
  }

  const blob = new Blob([content], { type: format === 'md' ? 'text/markdown;charset=utf-8' : 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  
  // Clean filename
  const cleanTitle = conversation.title
    .toLowerCase()
    .replace(/[^a-z0-9\s]+/g, '')
    .trim()
    .replace(/\s+/g, '_');
  
  a.download = `${cleanTitle || 'chat'}_export.${format}`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
